# Generated by Django 5.1.4 on 2025-02-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('photo', models.TextField(default='https://loremflickr.com/1280/720')),
                ('creator', models.TextField(default='John Doe')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('reactions', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('comments_list', models.TextField(default='[]')),
                ('category', models.TextField(default='Основні')),
                ('tags', models.TextField(default='[]')),
            ],
        ),
    ]
